### ISSUE TITLE
blender project for demo?

### ISSUE THREAD

**Issue by funnyQZQ** [srleohung/blender-pose-estimation#1]
Hi, I get the Vincent.blend file from your project. However, i can't reproduce the [demo](https://github.com/srleohung/blender-pose-estimation/blob/master/Demo.gif) you showed in Readme, could you please provide the blender project of the demo? 

Thanks a lot!

**Comment by srleohung** [comment]
The project is under development, but stopped at the beginning of the year. I am working on another project. If I finish, I will come back. Thanks for your support.
